### ISSUE TITLE
stis_cti fails to build in python 3.11 environment.

### ISSUE THREAD

**Issue by mgough-970** [spacetelescope/stis_cti#15]
Certain STIS notebooks contain stis_cti as a requirement, while installing dependencies in python 3.11, the following error was encountered.

Building wheel for stis_cti (setup.py): started
  Building wheel for stis_cti (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/StisPixCteCorr.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/stis_cti.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/unit_tests.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/custom_superdark_info.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/archive_dark_query.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      copying stis_cti/__init__.py -> build/lib.linux-x86_64-cpython-311/stis_cti
      creating build/lib.linux-x86_64-cpython-311/stis_cti/data
      copying stis_cti/data/a01_stis_pcte.fits -> build/lib.linux-x86_64-cpython-311/stis_cti/data
      running build_ext
      building 'stis_cti.StisPixCte_FixY' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/src
      gcc -pthread -B /usr/share/miniconda/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -I/usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include -Isrc/ -I/usr/share/miniconda/include/python3.11 -c src/StisFixYCte.c -o build/temp.linux-x86_64-cpython-311/src/StisFixYCte.o
      gcc -pthread -B /usr/share/miniconda/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -I/usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include -Isrc/ -I/usr/share/miniconda/include/python3.11 -c src/StisPixCteCorr_funcs.c -o build/temp.linux-x86_64-cpython-311/src/StisPixCteCorr_funcs.o
      src/StisPixCteCorr_funcs.c:66:71: warning: argument 2 of type ‘const int[17]’ with mismatched bound [-Warray-parameter=]
         66 | int InterpolatePsi(const double chg_leak[NUM_PSI*NUM_LOGQ], const int psi_node[NUM_PSI],
            |                                                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~
      In file included from src/StisPixCteCorr_funcs.c:7:
      src/StisPixCteCorr.h:22:71: note: previously declared as ‘const int[]’
         22 | int InterpolatePsi(const double chg_leak[NUM_PSI*NUM_LOGQ], const int psi_node[],
            |                                                             ~~~~~~~~~~^~~~~~~~~~
      gcc -pthread -B /usr/share/miniconda/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -O2 -isystem /usr/share/miniconda/include -fPIC -I/usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include -Isrc/ -I/usr/share/miniconda/include/python3.11 -c src/StisPixCte_FixY.c -o build/temp.linux-x86_64-cpython-311/src/StisPixCte_FixY.o
      In file included from /usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948,
                       from /usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from src/StisPixCte_FixY.c:5:
      /usr/share/miniconda/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      src/StisPixCte_FixY.c: In function ‘py_InterpolatePsi’:
      src/StisPixCte_FixY.c:80:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
         80 |     PyErr_SetString(PyExc_StandardError, "An error occurred in InterpolatePsi.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c:80:21: note: each undeclared identifier is reported only once for each function it appears in
      src/StisPixCte_FixY.c: In function ‘py_InterpolatePhi’:
      src/StisPixCte_FixY.c:124:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
        124 |     PyErr_SetString(PyExc_StandardError, "An error occurred in InterpolatePhi.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c: In function ‘py_FillLevelArrays’:
      src/StisPixCte_FixY.c:181:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
        181 |     PyErr_SetString(PyExc_StandardError, "An error occurred in FillLevelArrays.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c: In function ‘py_DecomposeRN’:
      src/StisPixCte_FixY.c:239:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
        239 |     PyErr_SetString(PyExc_StandardError, "An error occurred in DecomposeRN.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c: In function ‘py_FixYCte’:
      src/StisPixCte_FixY.c:314:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
        314 |     PyErr_SetString(PyExc_StandardError, "An error occurred in FixYCte.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c: In function ‘py_AddYCte’:
      src/StisPixCte_FixY.c:393:21: error: ‘PyExc_StandardError’ undeclared (first use in this function); did you mean ‘PyExc_SyntaxError’?
        393 |     PyErr_SetString(PyExc_StandardError, "An error occurred in AddYCte.");
            |                     ^~~~~~~~~~~~~~~~~~~
            |                     PyExc_SyntaxError
      src/StisPixCte_FixY.c: In function ‘initStisPixCte_FixY’:
      src/StisPixCte_FixY.c:424:10: warning: implicit declaration of function ‘Py_InitModule’ [-Wimplicit-function-declaration]
        424 |   (void) Py_InitModule("StisPixCte_FixY", StisPixCte_FixY_methods);
            |          ^~~~~~~~~~~~~
      src/StisPixCte_FixY.c:426:1: warning: control reaches end of non-void function [-Wreturn-type]
        426 | }
            | ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stis_cti
  Running setup.py clean for stis_cti
  Building wheel for stregion (pyproject.toml): started
  Building wheel for stregion (pyproject.toml): finished with status 'done'
  Created wheel for stregion: filename=stregion-1.1.7-cp311-cp311-linux_x86_64.whl size=1022142 sha256=04917934a761acbbbaffa6072b40781495ca1e64683180cb90b83f4bfd62cc01
  Stored in directory: /home/runner/.cache/pip/wheels/99/57/60/dd6b463d5ace63f61589a703914c42518c4c8c5df9f73340cc
  Building wheel for stsci.image (pyproject.toml): started
  Building wheel for stsci.image (pyproject.toml): finished with status 'done'
  Created wheel for stsci.image: filename=stsci.image-2.3.5-cp311-cp311-linux_x86_64.whl size=19890 sha256=3e5b5ca8df91bb8dcba80edb8fb7264705ee76756e586f195049349e[557](https://github.com/spacetelescope/hst_notebooks/actions/runs/6892413302/job/18749664399#step:6:558)e3df7
  Stored in directory: /home/runner/.cache/pip/wheels/32/41/d2/f66c01bfd3462f4c28309006eda2c2975024ce040217056b82
  Building wheel for stsci.imagestats (pyproject.toml): started
  Building wheel for stsci.imagestats (pyproject.toml): finished with status 'done'
  Created wheel for stsci.imagestats: filename=stsci.imagestats-1.6.3-cp311-cp311-linux_x86_64.whl size=16899 sha256=1e1b6bb4e47a5df9635afcb93215012da8b5b1b3db755c6e8f809230a4bfa998
  Stored in directory: /home/runner/.cache/pip/wheels/b7/39/ed/8b040bf2c7b89fe605d30a866dffb04ca3436e0c22c86765df
  Building wheel for stsci.stimage (pyproject.toml): started
  Building wheel for stsci.stimage (pyproject.toml): finished with status 'done'
  Created wheel for stsci.stimage: filename=stsci.stimage-0.2.6-cp311-cp311-linux_x86_64.whl size=49225 sha256=ed51c6c35adc404ac0882e19ba03827b73b86ac43278eff6974ce1e9bff3252f
  Stored in directory: /home/runner/.cache/pip/wheels/f0/43/2f/c4efe10974e23e626eefa3a87cd9629f583ae2d77ade3ce[558](https://github.com/spacetelescope/hst_notebooks/actions/runs/6892413302/job/18749664399#step:6:559)
Successfully built drizzlepac stregion stsci.image stsci.imagestats stsci.stimage
Failed to build stis_cti
ERROR: Could not build wheels for stis_cti, which is required to install pyproject.toml-based projects
Error: Process completed with exit code 1.

**Comment by sean-lockwood** [comment]
I'm able to build and install it manually in my local python 3.11 environment (Mac; arm64) using `python setup.py build` and `python setup.py install`.

The version on PyPI (1.1) is outdated, so I'm wondering if releasing the updated version will resolve this issue.

**Comment by sean-lockwood** [comment]
Build 1.5.2 uploaded to PyPI.  Works in python 3.11.
